/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseOrdering: typeof import('./src/components/BaseOrdering.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleDatatable: typeof import('./src/components/SimpleDatatable.vue')['default']
    VuetifyDatatable: typeof import('./src/components/VuetifyDatatable.vue')['default']
  }
}
